### ISSUE TITLE
Blocking specific email providers from even registering

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/drupal7-a2j#1]
We are getting a significant amount of spam from @epurus.com email addresses. Is there a way to block anyone who attempts to register with an @epurus.com account?

The email addresses are typically a website address@epurus.com (ex. one was Barbiesdreamhouse.com@epurus.com)

About 10-20 spam registrations a day in the last 3 days.

**Comment by emasters** [comment]
solved with user restrictions module.
