### ISSUE TITLE
Move login to footer, remove registration link

### ISSUE THREAD

**Issue by emasters** [CCALI/drupal7-a2j#10]
Since logins will be necessary for access to only a few things like A2J Author 5 and matching, the login space can be placed in the footer. Accessing certain content will display both the login and a registration link in a more prominent place.

**Comment by emasters** [comment]
Login moved to A2J Author page only.

**Comment by emasters** [comment]
Moved login link to first footer region on www. Currently appears only on 
`content/a2j-author
projects
organizations`
Should it appear everywhere?

**Comment by arabanal** [comment]
There should be a login also on "A2J Project Matching Portal."

**Comment by tobiasnteireho** [comment]
done or assumed no longer necessary
