### ISSUE TITLE
Figure out how the slideshow works

### ISSUE THREAD

**Issue by emasters** [CCALI/drupal7-a2j#12]
This is a procedural point that needs to be documented. Initial attempts at using the slideshow did not work as expected. The image and layout were off.

**Comment by JessicaFrank** [comment]
I tried again with this. Adding in an image of the map of states that use A2J Author. No luck.

**Comment by arabanal** [comment]
I've also done some testing on this feature but so far have had no luck.  Non-image block elements display accordingly, but the image file path appears problematic.  I referenced the slideshow image paths in the page source, and the images do not appear when clicked.

**Comment by emasters** [comment]
This is fixed! I hadn't copied over the necessary image styles when I set up the Scholarly theme. The image styles are now in place and the slideshow works as expected.
@jessicafrank @arabanal be sure to test it out.
