### ISSUE TITLE
Custom Project Posting Interface

### ISSUE THREAD

**Issue by arabanal** [CCALI/drupal7-a2j#18]
Create custom interface for posting A2J Author projects.  Posting projects through "Add content" may not be intuitive for most users.  Could be something like a form or widget.  Even with instructions, it's preferable to have a dedicated entry point for posting projects.

**Comment by emasters** [comment]
Agree that the typical Node->add->content path is not intuitive. I'd suggest a a button that says "Add a project" somewhere in the interface that appears when folks with the right permissions are logged in. That avoids needing to pick through the admin interface looking for things.

**Comment by arabanal** [comment]
Buttons added.
