### ISSUE TITLE
Entering and Sorting Jurisdictions

### ISSUE THREAD

**Issue by arabanal** [CCALI/drupal7-a2j#19]
I'm creating a separate issue for this topic, which was mentioned in a previous issue, which I've since closed.  

Can we control input for the jurisdiction field so that there aren't different versions for entering the same jurisdiction that would make them appear in a different sequence when sorted (e.g. AK / Alaska, NY / New York).  Perhaps a drop down list of states and an option to further clarify by adding context (e.g. city, county, court)?

**Comment by emasters** [comment]
Sure. That involves changing the jurisdiction field at d7dev.a2jauthor.org/admin/structure/types/manage/a2j-author-projects/fields/field_jurisdiction from a text field to a pick list and entering the state info as you'd like. Then another short text field for local context could be added. 
Note: changing a field's type is a destructive process. It needs to be deleted and readded resulting in the loss of data already in the system.

**Comment by arabanal** [comment]
Changed Jurisdiction field to pick list.  Added Specify Jurisdiction text field.
