### ISSUE TITLE
Is there a way to search users by name?

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/drupal7-a2j#2]
We are getting 50+ spam registrations a day. It is taking me at least an hour a day to go through them. It would be easier for me to authenticate actual users if I could search for their names in the mass of spam registrations. Currently I see I can sort users by role, permission, and status. I can also Control F search, but I have to do it page by page. Is there a way to add a search all users by name option?

**Comment by emasters** [comment]
Spam users are under control.
