### ISSUE TITLE
Add Tweet Panel or Stream

### ISSUE THREAD

**Issue by arabanal** [CCALI/drupal7-a2j#21]
This feature will be used to highlight tweets from CALI and A2J Author. 

Need to active Twitter API to manifest Twitter blocks?

**Comment by emasters** [comment]
Twitter access is available but needs to be set up at d7dev.a2jauthor.org/admin/config/services/twitter/settings.
Once set up we can do this.

**Comment by emasters** [comment]
This needs to be tied to the A2J twitter account.

**Comment by arabanal** [comment]
Created "Twitter for A2J Author" app and linked to dev site.  Twitter Updates view displayed in the second sidebar.  Can click through to full Twitter Updates view to see more tweets.
