### ISSUE TITLE
Make A2J App login like CALI Lessons 

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/drupal7-a2j#24]
Elmer said he'd remember what this meant -- make access to A2J Author the tool work like access to CALI Lessons.

**Comment by emasters** [comment]
Needs to display message letting folks they need to be registered and logged in to get to the link. Like we do with Lessons.

**Comment by JessicaFrank** [comment]
Does the language on this page work: http://d7dev.a2jauthor.org/content/a2j-author

**Comment by tobiasnteireho** [comment]
done a long time ago
