### ISSUE TITLE
Need the convert module to change content types 

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/drupal7-a2j#26]
In the conversion, some of the content types and content on the production site (and the old.a2jauthor.org) no longer correlate with the dev site. I want to be able to convert the content types (ex. from book page to FAQ) easily without having to replicate the content. 

I found this & thought we could install it?
https://www.drupal.org/node/2307815

**Comment by tobiasnteireho** [comment]
assumed no longer necessary
