### ISSUE TITLE
User registration and password are messed up

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/drupal7-a2j#29]
I created a test account to see if the emails were flowing properly (login toboggin spam email to activate account after creation, then email with registration webform to fill out after activated)

The user on creating the account isn't given a place to enter a password
![image](https://cloud.githubusercontent.com/assets/7662028/12100805/e515fed4-b2f6-11e5-861b-a4294a39b2e7.png)

Then they get an email that says "In the future you will be able to log in to http://d7dev.a2jauthor.org/user using the username and password that you created during registration.". I clicked the link in the activation email and am taken to this page where I try to make a password (since I don't have one on my account yet) and I can't. 

![website d7dev user creation](https://cloud.githubusercontent.com/assets/7662028/12100899/884ad0b6-b2f7-11e5-9acf-ad153c9728a3.gif)

**Comment by JessicaFrank** [comment]
I clicked "request new password" and was able to create a new password by opening the link in an incognito browser (it is not user friendly). 

No email was sent to be with the survey (supposed to be sent when account is activated)

**Comment by emasters** [comment]
Fixed the password part. New users now get to create password. Still looking into email flow, the post activation email to the survey not working.

**Comment by emasters** [comment]
Imported the user validation rule from www and added link to webform. Seems to be working. @JessicaFrank Please test and close this if it's working as you want.

**Comment by JessicaFrank** [comment]
Works great!
