### ISSUE TITLE
Need to add a way to log out 

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/drupal7-a2j#30]
When I was in a non-admin account (testing out the user registration process), I wasn't able to log out. I think we need to add a log out box to the bottom block -- we are pretty much the only ones who will need it, but it should still exist. 

Will work on adding this after we migrate the site over to production.

**Comment by emasters** [comment]
I was already working on this. :)
I added a block with username and a logout link so if you're logged in you can log out.
