### ISSUE TITLE
Need to change drupal logo to a2j logo in browser tab

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/drupal7-a2j#31]
The new website has the drupal icon in the browser tab, not the a2j logo.

**Comment by arabanal** [comment]
Uploaded A2J logo as favicon but still not displaying.

**Comment by arabanal** [comment]
Retried file upload but A2J favicon still not displaying.  May need to change file path.

**Comment by arabanal** [comment]
Changed favicon for Scholarly theme.
