### ISSUE TITLE
Delete events that have passed

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/drupal7-a2j#37]
Created a view on front page that displays the events we have coming up. 

How to delete (hopefully automatically) or hide events that have already happened?

**Comment by JessicaFrank** [comment]
Unpublishing the event doesn't do the trick. I'd like to be able to retain the event for a legacy listing of what we have done, but don't want the front page to look outdated as soon as an event is over.

**Comment by arabanal** [comment]
Changed filter on the Events Calendar view based on the end date + 1 day.  Since no events have been recently posted, the events calendar does not currently show on the home page.  Might look into whether it's possible to display descriptive content (e.g. "Check back soon").
