### ISSUE TITLE
User created account not showing up in system

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/drupal7-a2j#39]
User contacted me about an account she created on www.a2jauthor.org. She went to log in and it didn't work. She tried password reset and the system said the email she used wasn't associated with an account. 

When I searched for her in the Advanced People search, she wasn't in there at all. (by name or email address)

She had an email from webmaster@a2jauthor.org from 2/3/16 that said "Thank you for registering." and included the user validation information. 

Is the issue that she didn't click the validation email link in enough time? What is the window of time someone has to click that before their account is deleted? 

If it is this short, I think I should add a note about that in the auto pushed email to let them know to do it in 24 hours or 3 days, whatever it is.

**Comment by emasters** [comment]
The deletion period is 24 hours. That is most likely that happened in this case. I updated the email that is sent out to let folks know they only have 24 hours to validate their account or else it will be deleted and they will need to register again.
