### ISSUE TITLE
Restrict Projects and Organizations Pages

### ISSUE THREAD

**Issue by arabanal** [CCALI/drupal7-a2j#45]
Consider restricting Projects and Organizations pages to those who have registered on the site (and perhaps those who have proper matching portal permissions).

**Comment by arabanal** [comment]
Restricted pages and added user logins to both sidebars.

**Comment by arabanal** [comment]
Is it possible to have "Access Denied" and "You are not authorized to access this page" removed similar to the block on the A2J Author page, which does not contain that language?

**Comment by emasters** [comment]
The setup for these pages is more complicated than the A2J Author page. The author page is just a blank page with 2 blocks that show depending on whether or not a visitor is logged in. The org and project pages are Views, the access denied message is what gets generated when access control kicks in. 
One approach might be to have the View generate a block with the restricted content and then use the same approach as the author page.

**Comment by arabanal** [comment]
Sounds good.  I'd like to mimic the A2J Author page setup as much as possible.

**Comment by emasters** [comment]
Fixed for organizations. Using the `Organizations Info` block for the anon page and the `View:Organizations` block for the privileged page. Created a blank page called `Organizations` to hold the blocks.

**Comment by emasters** [comment]
Fixed for projects. Using the Projects Info block for the anon page and the View:Projects Block block for the privileged page. Created a blank page called Projects to hold the blocks.
