### ISSUE TITLE
Push Email to Organization Creator

### ISSUE THREAD

**Issue by arabanal** [CCALI/drupal7-a2j#46]
Push email to the creator of an Organization each time a project has been posted for their organization.  This will provide notice and offer them a way to correct any project postings that do not belong to their organization.

**Comment by emasters** [comment]
Will handle this with a Rule.
@arabanal Anything in particular you'd like to have in the email?

**Comment by arabanal** [comment]
A confirmation message that the organization has added a project.  Also, a message stating that if this was created in error, to send an email to webmaster (or even better would be an account that handles just inquiries for the matching tool that could get pushed to me.)

**Comment by emasters** [comment]
Put rule in place to send email to org owner when a project is added. To test made @arabanal owner of CALI org on www and added a project linked to the org. He should get an email.

**Comment by arabanal** [comment]
@emasters I can confirm receipt of the email.

**Comment by emasters** [comment]
If the email text is fine this issue can be closed.
