### ISSUE TITLE
Role for Portal Users

### ISSUE THREAD

**Issue by arabanal** [CCALI/drupal7-a2j#47]
Create new role for portal users.  Separate registration process for those who wish to use portal.

**Comment by emasters** [comment]
Right now the following message goes out to _everyone_ who validates an account on the A2J site:

```
[account:name],

Your account at the [site:name] has been validated. To access the A2J Author 5.0 tool, you will need to be an authenticated author. To have a site administrator review your account and authenticate you, please fill out the following A2J Author 5.0 Registration form:  http://www.a2jauthor.org/content/a2j-author-authentication

The review process can take up to 2 business days. You will receive an email when you are authenticated as an A2J Author. 

If you have any questions, please email webmaster@a2jauthor.org. 
```
Do you want to add a link to another separate form to the validation email?

**Comment by arabanal** [comment]
I've been thinking about this, and we can incentivize A2J Author use by just using the same form.  So, if you want to sign up for the matching portal, just sign up for A2J Author.  It could also streamline registrations.   

Any pros you see for doing a separate form for the matching portal?

**Comment by emasters** [comment]
I see no pros for having a separate form at this point. I'd extend the current form to include the matching component and add text to the validation email letting folks know they can use it for matching too.

**Comment by arabanal** [comment]
Sounds good.  I like using one form / process also.

**Comment by emasters** [comment]
And what about the role? Just use the existing a2j author role?

**Comment by arabanal** [comment]
Yeah, let's use the A2J Author role.
