### ISSUE TITLE
How does someone get into the organization/project section of the site?

### ISSUE THREAD

**Issue by emasters** [CCALI/drupal7-a2j#48]
Should this be included in the menu system somewhere?

**Comment by arabanal** [comment]
I think there should be a tab.  The portal itself is really the Projects page, but I think it would be good to direct to the landing page, "A2J Project Matching Portal," for some context, especially since we're rolling it out.

**Comment by arabanal** [comment]
The menu structure should be Main Tab > A2J Project Matching Portal with drop downs for "Projects" and "Organizations."

**Comment by emasters** [comment]
`A2J Project Matching Portal` pretty much doubles the word count of the main menu. Would `Matching` work?

**Comment by arabanal** [comment]
Matching would work.  I would hold off enabling this menu item until early next week, when I hope to launch the portal.
