### ISSUE TITLE
Streamlined click path to edit Projects

### ISSUE THREAD

**Issue by arabanal** [CCALI/drupal7-a2j#49]
Once the project is matched, the organization is supposed to change availability from "Yes" to "No." We don't want users, particularly those unfamiliar with Drupal, clicking around trying to find the project content just to make that change.  Is there an easier way to direct them to the content?  We'll probably need to just give instructions.

**Comment by emasters** [comment]
From the project page they just need to hit the `edit` tab and change the availability.

**Comment by arabanal** [comment]
Perfect, it slipped my mind that the view would easily generate for them.  I'll close.
