### ISSUE TITLE
Display Column Label for Name of Form

### ISSUE THREAD

**Issue by arabanal** [CCALI/drupal7-a2j#51]
On the Project Block, the column label does not appear for the name of the form.  I created a label for this on the Projects page, but even when I check the option to create a label in the block, it does not populate a field to add the label.

**Comment by arabanal** [comment]
@emasters May need to roll back version of jQuery to remedy.

**Comment by emasters** [comment]
Fixed this on http://www.a2jauthor.org/projects by adding a another `content:title` field with a label of `Title` and then removing the broken field.
