### ISSUE TITLE
Can't log into a2jauthor.org via mobile browser

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/drupal7-a2j#6]
I tried logging into a2jauthor.org yesterday because I was going through my emails on my phone and I wanted to deal with some of the webmaster spam registrations while I was on the train. 

I couldn't log into the website because of the way the webpage looks on a mobile browser. I couldn't access the "login" button at the top of the page. I tried pinching it to make it smaller and moving the screen around to get to the top right corner to access the login button, but I couldn't. 

Since we are thinking Mobile in general, I think we need to optimize our main website for mobile usage as well.  

Not sure if this is a simple design thing or something bigger. Just putting the info out there.

**Comment by emasters** [comment]
The new theme will handle mobile. I'm leaving this open so we remember to include mobile in testing.

**Comment by emasters** [comment]
Works on dev. Closing.
