### ISSUE TITLE
Registration Process Text

### ISSUE THREAD

**Issue by arabanal** [CCALI/drupal7-a2j#7]
I'm requesting that the following text be added to the registration form to inform registrants of the authentication process so that they know when to expect access to A2J Author: 

"After signing up, you will receive an email to validate your account.  You will then receive a follow-up email with a brief survey required for authentication.  Registrations will be authenticated during normal business hours, CST."

**Comment by emasters** [comment]
This will get worked into the new rule set up in the new version.
