### ISSUE TITLE
Notifications when users post questions

### ISSUE THREAD

**Issue by JessicaFrank** [CCALI/drupal7-a2j#9]
Hi,

Is there a way to turn on notifications when a user posts a question to the questions page: http://a2jauthor.org/questions

This is a customer service issue in that sometimes these get lost because Alex and I aren't notified when they come in. We have to manually check the page for new questions. Ideally, we like the notifications to go to webmaster@a2jauthor.org so that either of us can manage it.

**Comment by emasters** [comment]
Fixed. When questions are created email now goes to webmaster@a2jauthor.org.
